# Generated by Django 5.2.4 on 2025-07-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0002_cabinetrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabinetRole',
        ),
    ]
