# Generated by Django 5.2.4 on 2025-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0003_delete_cabinetrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='association',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='associations/logos/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/receipts/'),
        ),
    ]
