# Generated by Django 5.2.4 on 2025-09-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0004_remove_association_logo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='theme_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.CreateModel(
            name='AssociationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='campus_nexus.association')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='association_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
