# Generated by Django 5.2.4 on 2025-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0005_association_theme_color_associationadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='association',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='association',
            name='theme_css_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='associations/themes/'),
        ),
    ]
