# Generated by Django 5.2.4 on 2025-09-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0006_alter_faculty_options_feedback'),
        ('campus_nexus', '0006_alter_faculty_options_remove_association_theme_color_and_more'),
    ]

    operations = [
    ]
