# Generated by Django 5.2.4 on 2025-10-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0007_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='campus_nexus.association'),
        ),
    ]
