# Generated by Django 5.2.4 on 2025-10-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0007_guild'),
        ('campus_nexus', '0007_merge_20250922_0616'),
    ]

    operations = [
    ]
