# Generated by Django 5.2.4 on 2025-10-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0008_alter_cabinet_association'),
        ('campus_nexus', '0008_merge_0007_guild_0007_merge_20250922_0616'),
    ]

    operations = [
    ]
