# Generated by Django 5.2.4 on 2026-02-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0010_member_created_by_member_created_in_association_dean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('member', 'association'), name='unique_member_per_association'),
        ),
    ]
