# Generated by Django 5.2.4 on 2026-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0011_alter_member_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
