# Generated by Django 5.2.4 on 2026-02-11 17:09

from email.policy import default
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0014_guildcabinet_guildannouncement_guildminister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildcabinet',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='guildminister',
            options={'ordering': ('ministry',)},
        ),
        migrations.RemoveField(
            model_name='guildminister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guildminister',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='guildminister',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='guildminister',
            name='photo',
        ),
        migrations.AddField(
            model_name='guildcabinet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildminister',
            name='appointed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildminister',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guild_roles', to='campus_nexus.member'),
            preserve_default=False,
        ),
    ]
