# Generated by Django 5.2.4 on 2026-02-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0015_alter_guildcabinet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildannouncement',
            name='created_by',
        ),
        migrations.CreateModel(
            name='AssociationLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_photo', models.ImageField(blank=True, null=True, upload_to='associations/presidents/')),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='campus_nexus.association')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_of', to='campus_nexus.member')),
            ],
        ),
        migrations.CreateModel(
            name='GuildExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('guild_president', 'Guild President'), ('prime_minister', 'Prime Minister'), ('lady_vice', 'Lady Vice'), ('vice_lady_vice', 'Vice Lady Vice'), ('minister', 'Minister')], max_length=30)),
                ('ministry', models.CharField(blank=True, default='', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guild/executives/')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='campus_nexus.guildcabinet')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_positions', to='campus_nexus.member')),
            ],
            options={
                'ordering': ('position_type', 'ministry'),
            },
        ),
        migrations.AddField(
            model_name='guildannouncement',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='campus_nexus.guildexecutive'),
        ),
        migrations.DeleteModel(
            name='GuildMinister',
        ),
        migrations.AddConstraint(
            model_name='guildexecutive',
            constraint=models.UniqueConstraint(condition=models.Q(('position_type__in', ['guild_president', 'prime_minister', 'lady_vice', 'vice_lady_vice'])), fields=('cabinet', 'position_type'), name='unique_top_positions_per_cabinet'),
        ),
        migrations.AddConstraint(
            model_name='guildexecutive',
            constraint=models.UniqueConstraint(condition=models.Q(('position_type', 'minister')), fields=('cabinet', 'ministry'), name='unique_ministry_per_cabinet'),
        ),
    ]
