# Generated by Django 5.2.4 on 2026-02-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0016_remove_guildannouncement_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationadmin',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='associationadmin',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='associations/presidents/'),
        ),
        migrations.AddField(
            model_name='associationadmin',
            name='title',
            field=models.CharField(blank=True, default='Association Admin', max_length=80),
        ),
        migrations.DeleteModel(
            name='AssociationLeadership',
        ),
    ]
