# Generated by Django 5.2.4 on 2026-02-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0017_associationadmin_bio_associationadmin_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guildexecutive',
            name='unique_top_positions_per_cabinet',
        ),
        migrations.RemoveConstraint(
            model_name='guildexecutive',
            name='unique_ministry_per_cabinet',
        ),
        migrations.AddField(
            model_name='guildexecutive',
            name='reports_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'position_type': 'minister'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', to='campus_nexus.guildexecutive'),
        ),
        migrations.AlterField(
            model_name='guildexecutive',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_executive_roles', to='campus_nexus.member'),
        ),
        migrations.AlterField(
            model_name='guildexecutive',
            name='position_type',
            field=models.CharField(choices=[('guild_president', 'Guild President'), ('lady_vice', 'Lady Vice President'), ('vice_lady_vice', 'Vice Lady Vice President'), ('prime_minister', 'Prime Minister'), ('minister', 'Minister'), ('state_minister', 'State Minister (Deputy)')], max_length=30),
        ),
    ]
