# Generated by Django 5.2.4 on 2026-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0018_remove_guildexecutive_unique_top_positions_per_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildexecutive',
            options={'ordering': ('sort_order', 'ministry', 'member__first_name')},
        ),
        migrations.AddField(
            model_name='guildexecutive',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=1000),
        ),
    ]
