# Generated by Django 5.2.4 on 2026-02-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0020_rename_payment_date_payment_recorded_at_payment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='allow_installments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='grace_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fee',
            name='max_missed_cycles',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='fee',
            name='reminder_days_before_due',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membership',
            name='discard_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membership',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('discarded', 'Discarded')], max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('before_due', 'Before Due'), ('overdue', 'Overdue'), ('final_warning', 'Final Warning')], max_length=30)),
                ('scheduled_for', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='campus_nexus.charge')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='campus_nexus.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('charge', 'reminder_type', 'scheduled_for'), name='unique_reminder_per_charge_per_day')],
            },
        ),
    ]
