# Generated by Django 5.2.4 on 2026-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0021_charge_is_overdue_charge_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campus_nexus.charge'),
        ),
    ]
