# Generated by Django 5.2.4 on 2026-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0023_announcement_delete_guildannouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='discard_reason',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='discarded_at',
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscription_anchor_date',
            field=models.DateField(blank=True, help_text='Start date used to calculate subscription cycles. Leave blank to use today.', null=True),
        ),
    ]
