# Generated by Django 5.2.4 on 2026-02-18 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0024_remove_membership_discard_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('membership', 'fee', 'period_start', 'period_end'), name='uniq_charge_per_cycle'),
        ),
    ]
