# Generated by Django 5.2.4 on 2026-02-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0025_charge_uniq_charge_per_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='reminder_days_before_due',
        ),
    ]
