# Generated by Django 5.2.4 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0026_remove_fee_reminder_days_before_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='reminder_days_before_due',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
