# Generated by Django 5.2.4 on 2026-02-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0027_fee_reminder_days_before_due'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='campus_nexus.association')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='campus_nexu_created_5a6b98_idx'), models.Index(fields=['action'], name='campus_nexu_action_5d20e6_idx'), models.Index(fields=['model_name'], name='campus_nexu_model_n_f7ecb2_idx'), models.Index(fields=['association', 'created_at'], name='campus_nexu_associa_18b2db_idx')],
            },
        ),
    ]
