# Generated by Django 5.2.4 on 2026-02-23 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0028_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('operations', 'Operations'), ('event', 'Event'), ('logistics', 'Logistics'), ('welfare', 'Welfare'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20)),
                ('payee', models.CharField(blank=True, default='', max_length=150)),
                ('reference_code', models.CharField(blank=True, default='', max_length=120)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('description', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('reversed', 'Reversed')], default='recorded', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='campus_nexus.association')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-spent_at', '-recorded_at'),
                'indexes': [models.Index(fields=['association', 'spent_at'], name='campus_nexu_associa_21c558_idx'), models.Index(fields=['status'], name='campus_nexu_status_fd0a1d_idx'), models.Index(fields=['category'], name='campus_nexu_categor_1ffdd9_idx')],
            },
        ),
    ]
