# Generated by Django 5.2.4 on 2026-02-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0029_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildcabinet',
            name='name',
            field=models.CharField(default='Guild Cabinet', max_length=120),
        ),
    ]
