# Generated by Django 5.2.4 on 2026-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0031_member_photo_alter_member_nationality'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='membership',
            name='unique_member_per_association',
            constraint=models.UniqueConstraint(fields=('member', 'association'), name='unique_member_per_association', violation_error_message='This member is already registered in this association. Use the existing membership record instead of creating a duplicate.'),
        ),
    ]
