# Generated by Django 5.2.4 on 2026-05-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0035_alter_member_nationality_billableitem_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill_membership',
        ),
        migrations.AddField(
            model_name='billmembership',
            name='amount_waived',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='charge',
            name='bill_membership',
            field=models.ForeignKey(blank=True, help_text='Link to bill membership (new billing system)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='campus_nexus.billmembership'),
        ),
    ]
