# Generated by Django 5.2.4 on 2026-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0036_remove_payment_bill_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount per member. Leave blank to auto-fill from billable item.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(blank=True, help_text='Override billable item name if needed. Leave blank to auto-fill.', max_length=200),
        ),
    ]
