# Generated by Django 5.2.4 on 2026-06-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0035_alter_member_nationality'),
        ('campus_nexus', '0037_alter_bill_amount_alter_bill_title'),
    ]

    operations = [
    ]
