# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_nexus", "0038_merge_20260611_0137"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="theme_primary_color",
            field=models.CharField(blank=True, default="", editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name="association",
            name="theme_secondary_color",
            field=models.CharField(blank=True, default="", editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name="association",
            name="theme_version",
            field=models.CharField(blank=True, default="", editable=False, max_length=12),
        ),
    ]
