# Generated by Django 5.2.4 on 2026-07-08 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0040_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved_pending_payment', 'Approved - Pending Payment'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=32)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='campus_nexus.association')),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_application', to='campus_nexus.charge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='campus_nexus.member')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='campus_nexus.membership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_membership_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-applied_at',),
                'indexes': [models.Index(fields=['member', 'status'], name='campus_nexu_member__b9a573_idx'), models.Index(fields=['association', 'status'], name='campus_nexu_associa_519d18_idx'), models.Index(fields=['applied_at'], name='campus_nexu_applied_383334_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'approved_pending_payment'])), fields=('member', 'association'), name='unique_open_membership_application')],
            },
        ),
    ]
