# Generated by Django 5.2.4 on 2026-07-08 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0041_membershipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='AssociationPaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=20)),
                ('payment_location', models.CharField(max_length=200)),
                ('pay_to', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_instructions', to='campus_nexus.association')),
            ],
            options={
                'ordering': ('association__name', 'payment_method', '-is_active', '-updated_at'),
                'indexes': [models.Index(fields=['association', 'payment_method', 'is_active'], name='campus_nexu_associa_5e15c2_idx')],
            },
        ),
    ]
