# Generated by Django 5.2.4 on 2026-07-08 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0042_alter_payment_reference_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('account', 'Account'), ('membership', 'Membership'), ('application', 'Application'), ('payment', 'Payment'), ('event', 'Event'), ('announcement', 'Announcement'), ('system', 'System')], default='system', max_length=24)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, default='', max_length=255)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=120)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('deduplication_key', models.CharField(blank=True, max_length=180, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='campus_nexu_recipie_214ef5_idx'), models.Index(fields=['recipient', 'created_at'], name='campus_nexu_recipie_0fadec_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'deduplication_key'), name='unique_notification_dedup_per_recipient')],
            },
        ),
    ]
