# Generated by Django 5.2.4 on 2026-07-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0043_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_notifications', models.BooleanField(default=True)),
                ('announcement_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='campus_nexus.member')),
            ],
            options={
                'ordering': ('member__first_name', 'member__last_name', 'member_id'),
            },
        ),
    ]
