# Generated by Django 5.2.4 on 2026-07-08 14:59

import uuid
from django.db import migrations, models


def populate_membership_verification_tokens(apps, schema_editor):
    Membership = apps.get_model("campus_nexus", "Membership")
    for membership in Membership.objects.filter(verification_token__isnull=True).iterator():
        token = uuid.uuid4()
        while Membership.objects.filter(verification_token=token).exists():
            token = uuid.uuid4()
        membership.verification_token = token
        membership.save(update_fields=["verification_token"])


def clear_membership_verification_tokens(apps, schema_editor):
    Membership = apps.get_model("campus_nexus", "Membership")
    Membership.objects.update(verification_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0044_membernotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='verification_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_membership_verification_tokens,
            clear_membership_verification_tokens,
        ),
        migrations.AlterField(
            model_name='membership',
            name='verification_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
