# Generated by Django 5.2.4 on 2026-07-08 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nexus', '0045_membership_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('transition_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='campus_nexus.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='campus_nexus.member')),
            ],
            options={
                'ordering': ('-registered_at', '-id'),
                'indexes': [models.Index(fields=['member', 'status'], name='campus_nexu_member__6a82f8_idx'), models.Index(fields=['event', 'status'], name='campus_nexu_event_i_a10dd2_idx'), models.Index(fields=['registered_at'], name='campus_nexu_registe_d27f5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_event_registration_per_member')],
            },
        ),
    ]
