from __future__ import annotations

from pathlib import Path


ISO3166_TAB_PATH = Path("/usr/share/zoneinfo/iso3166.tab")

FALLBACK_COUNTRY_NAMES = [
    "Uganda",
    "Kenya",
    "Tanzania",
    "Rwanda",
    "Burundi",
    "South Sudan",
    "Democratic Republic of the Congo",
    "Nigeria",
    "Ghana",
    "South Africa",
    "Egypt",
    "Sudan",
    "Ethiopia",
    "United States",
    "United Kingdom",
    "Canada",
    "India",
    "Pakistan",
    "Bangladesh",
    "China",
    "Japan",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Saudi Arabia",
    "United Arab Emirates",
    "Qatar",
    "Australia",
    "New Zealand",
]

COUNTRY_NATIONALITY_LABELS = {
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "Andorra": "Andorran",
    "Angola": "Angolan",
    "Argentina": "Argentinian",
    "Armenia": "Armenian",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Azerbaijan": "Azerbaijani",
    "Bahamas": "Bahamian",
    "Bahrain": "Bahraini",
    "Bangladesh": "Bangladeshi",
    "Barbados": "Barbadian",
    "Belarus": "Belarusian",
    "Belgium": "Belgian",
    "Belize": "Belizean",
    "Benin": "Beninese",
    "Bhutan": "Bhutanese",
    "Bolivia": "Bolivian",
    "Bosnia & Herzegovina": "Bosnian",
    "Botswana": "Motswana",
    "Brazil": "Brazilian",
    "Britain (UK)": "British",
    "Brunei": "Bruneian",
    "Bulgaria": "Bulgarian",
    "Burkina Faso": "Burkinabe",
    "Burundi": "Burundian",
    "Cambodia": "Cambodian",
    "Cameroon": "Cameroonian",
    "Canada": "Canadian",
    "Cape Verde": "Cape Verdean",
    "Central African Rep.": "Central African",
    "Chad": "Chadian",
    "Chile": "Chilean",
    "China": "Chinese",
    "Colombia": "Colombian",
    "Comoros": "Comorian",
    "Congo (Dem. Rep.)": "Congolese",
    "Congo (Rep.)": "Congolese",
    "Costa Rica": "Costa Rican",
    "Croatia": "Croatian",
    "Cuba": "Cuban",
    "Cyprus": "Cypriot",
    "Czech Republic": "Czech",
    "Côte d’Ivoire": "Ivorian",
    "Denmark": "Danish",
    "Djibouti": "Djiboutian",
    "Dominica": "Dominican",
    "Dominican Republic": "Dominican",
    "Ecuador": "Ecuadorian",
    "Egypt": "Egyptian",
    "El Salvador": "Salvadoran",
    "Equatorial Guinea": "Equatorial Guinean",
    "Eritrea": "Eritrean",
    "Estonia": "Estonian",
    "Eswatini (Swaziland)": "Swazi",
    "Ethiopia": "Ethiopian",
    "Fiji": "Fijian",
    "Finland": "Finnish",
    "France": "French",
    "Gabon": "Gabonese",
    "Gambia": "Gambian",
    "Georgia": "Georgian",
    "Germany": "German",
    "Ghana": "Ghanaian",
    "Greece": "Greek",
    "Grenada": "Grenadian",
    "Guatemala": "Guatemalan",
    "Guinea": "Guinean",
    "Guinea-Bissau": "Bissau-Guinean",
    "Guyana": "Guyanese",
    "Haiti": "Haitian",
    "Honduras": "Honduran",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Iran": "Iranian",
    "Iraq": "Iraqi",
    "Ireland": "Irish",
    "Israel": "Israeli",
    "Italy": "Italian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Jordan": "Jordanian",
    "Kazakhstan": "Kazakhstani",
    "Kenya": "Kenyan",
    "Kiribati": "I-Kiribati",
    "Korea (North)": "North Korean",
    "Korea (South)": "South Korean",
    "Kuwait": "Kuwaiti",
    "Kyrgyzstan": "Kyrgyzstani",
    "Laos": "Lao",
    "Latvia": "Latvian",
    "Lebanon": "Lebanese",
    "Lesotho": "Basotho",
    "Liberia": "Liberian",
    "Libya": "Libyan",
    "Liechtenstein": "Liechtensteiner",
    "Lithuania": "Lithuanian",
    "Luxembourg": "Luxembourger",
    "Madagascar": "Malagasy",
    "Malawi": "Malawian",
    "Malaysia": "Malaysian",
    "Maldives": "Maldivian",
    "Mali": "Malian",
    "Malta": "Maltese",
    "Marshall Islands": "Marshallese",
    "Mauritania": "Mauritanian",
    "Mauritius": "Mauritian",
    "Mexico": "Mexican",
    "Micronesia": "Micronesian",
    "Moldova": "Moldovan",
    "Monaco": "Monegasque",
    "Mongolia": "Mongolian",
    "Montenegro": "Montenegrin",
    "Morocco": "Moroccan",
    "Mozambique": "Mozambican",
    "Myanmar (Burma)": "Burmese",
    "Namibia": "Namibian",
    "Nauru": "Nauruan",
    "Nepal": "Nepalese",
    "Netherlands": "Dutch",
    "New Zealand": "New Zealander",
    "Nicaragua": "Nicaraguan",
    "Niger": "Nigerien",
    "Nigeria": "Nigerian",
    "North Macedonia": "Macedonian",
    "Norway": "Norwegian",
    "Oman": "Omani",
    "Pakistan": "Pakistani",
    "Palau": "Palauan",
    "Palestine": "Palestinian",
    "Panama": "Panamanian",
    "Papua New Guinea": "Papua New Guinean",
    "Paraguay": "Paraguayan",
    "Peru": "Peruvian",
    "Philippines": "Filipino",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Qatar": "Qatari",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Rwanda": "Rwandan",
    "Samoa (western)": "Samoan",
    "San Marino": "Sammarinese",
    "Sao Tome & Principe": "Sao Tomean",
    "Saudi Arabia": "Saudi",
    "Senegal": "Senegalese",
    "Serbia": "Serbian",
    "Seychelles": "Seychellois",
    "Sierra Leone": "Sierra Leonean",
    "Singapore": "Singaporean",
    "Slovakia": "Slovak",
    "Slovenia": "Slovenian",
    "Solomon Islands": "Solomon Islander",
    "Somalia": "Somali",
    "South Africa": "South African",
    "South Sudan": "South Sudanese",
    "Spain": "Spanish",
    "Sri Lanka": "Sri Lankan",
    "Sudan": "Sudanese",
    "Suriname": "Surinamese",
    "Sweden": "Swedish",
    "Switzerland": "Swiss",
    "Syria": "Syrian",
    "Taiwan": "Taiwanese",
    "Tajikistan": "Tajikistani",
    "Tanzania": "Tanzanian",
    "Thailand": "Thai",
    "Togo": "Togolese",
    "Tonga": "Tongan",
    "Trinidad & Tobago": "Trinidadian",
    "Tunisia": "Tunisian",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "Tuvalu": "Tuvaluan",
    "Uganda": "Ugandan",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Emirati",
    "United Kingdom": "British",
    "United States": "American",
    "Uruguay": "Uruguayan",
    "Uzbekistan": "Uzbekistani",
    "Vanuatu": "Ni-Vanuatu",
    "Vatican City": "Vatican",
    "Venezuela": "Venezuelan",
    "Vietnam": "Vietnamese",
    "Yemen": "Yemeni",
    "Zambia": "Zambian",
    "Zimbabwe": "Zimbabwean",
}

COUNTRY_CODE_NATIONALITY_LABELS = {
    "UG": "Ugandan",
}


def _load_country_names() -> list[str]:
    if ISO3166_TAB_PATH.exists():
        country_names: list[str] = []
        with ISO3166_TAB_PATH.open(encoding="utf-8") as source:
            for line in source:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t", 1)
                if len(parts) != 2:
                    continue
                country_names.append(parts[1].strip())
        if country_names:
            return sorted(dict.fromkeys(country_names))
    return sorted(FALLBACK_COUNTRY_NAMES)


NATIONALITY_NAMES = sorted(
    dict.fromkeys(COUNTRY_NATIONALITY_LABELS.get(country_name, country_name) for country_name in _load_country_names())
)

COUNTRY_CHOICES = [("", "Select nationality")] + [
    (nationality_name, nationality_name) for nationality_name in NATIONALITY_NAMES
]

# Case-insensitive lookup to normalize imported CSV values.
COUNTRY_LOOKUP = {
    lookup_value.lower(): nationality_name
    for country_name in _load_country_names()
    for nationality_name in (COUNTRY_NATIONALITY_LABELS.get(country_name, country_name),)
    for lookup_value in (country_name, nationality_name)
}
COUNTRY_LOOKUP.update(
    {country_code.lower(): nationality_name for country_code, nationality_name in COUNTRY_CODE_NATIONALITY_LABELS.items()}
)
